# Generated by Django 5.1.3 on 2025-01-21 21:43

from django.db import migrations, models

class Migration(migrations.Migrations):
    dependencies = [
        ('folder_aplikacji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pseudonim',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]